VAR professional = 0
VAR friendly = 0
VAR agressive = 0
VAR location = false
VAR hitTeller1 = false
VAR sweetOnLinda = false
VAR constructionSite = false
VAR ladyFriend = false
VAR armed = false
VAR notAlone = false
VAR licensePlates = false
VAR DispatchConstructionSite=false
VAR DispatchLadyFriend = false
VAR DispatchArmed=false
VAR DispatchLicensePlates = false
VAR DispatchNotAlone = false
VAR ShotLeo = false
VAR statueFound = false
VAR confession = false